### ISSUE TITLE
Fit to screen 128x160 with ST7735

### ISSUE THREAD

**Issue by bulentperktas** [jamesdanielv/thermalcam#1]
Hello,

i am trying to do fitting thermal data on ST7735 TFT which resolution is 128x160 pixels, but your codes fit 128x128 resolution, How can i fit with it?

Thank You
Bulent PERKTAS

**Comment by jamesdanielv** [comment]
hello the driver might not define tft.width and tft.height
the released standard fork relies on the tft.width and the tft.height and div by 8 each


try changing these lines
#define    displayPixelWidth  tft.width() /8  //allows values to be hardcoded
#define    displayPixelHeight   tft.height() / 8

to 
#define    displayPixelWidth 128 /8  //allows values to be hardcoded
#define    displayPixelHeight  160 / 8

see if this works.

there also is a beta version of code, but its drivers are specific to the st7735 with 128x128 res and it provides double the speed. 

if you still want 128x128 and use the additional area for other purposes then just make sure the 


displayPixelHeight is defined as such that the display divide is 16 x16 pixel blocks. i think the code references this when it sub divides and computes smaller pixels.

**Comment by jamesdanielv** [comment]
i have a version loaded at thermal_camjuly2020.zip that works for 128x160 displays. it only moves the thermal cam color bar down and the text writing down, and it allows for Fahrenheit temps yp to 130deg now.
